#!/usr/bin/env python3
"""Cross-platform PyInstaller wrapper for DocConvert.

The script writes a small spec on the fly (so we can keep the canonical
``DocConvert.spec`` untouched) and invokes ``pyinstaller``. The output
directory is normalised to ``dist/DocConvert-<platform>-<arch>`` so the
release workflow can upload one binary per OS without collisions.

Usage:
    python build_scripts/build_exe.py            # builds for current platform
    python build_scripts/build_exe.py --onedir   # emit an onedir bundle instead of a single exe
"""

from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROOT_STR = str(ROOT)
SPEC_PATH = ROOT / "build_scripts" / "DocConvert.generated.spec"
DIST_NAME = "DocConvert"


def _platform_tag() -> str:
    system = platform.system().lower()
    machine = platform.machine().lower() or "unknown"
    if system == "windows":
        return f"windows-{machine}"
    if system == "darwin":
        return f"macos-{machine}"
    if system == "linux":
        return f"linux-{machine}"
    return f"{system}-{machine}"


def _render_spec(*, onefile: bool) -> str:
    target_name = DIST_NAME if onefile else f"{DIST_NAME}-onedir"
    collect_block = ""
    if not onefile:
        collect_block = f"""
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{target_name}',
)
"""
    return f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by build_scripts/build_exe.py - do not edit by hand.
from pathlib import Path
from PyInstaller.utils.hooks import collect_all

__ROOT_PATH__ = Path({ROOT_STR!r})

datas = []
binaries = []
hiddenimports = ['mammoth', 'docx', 'pandas', 'openpyxl', 'bs4', 'markdownify']
for module in ('mammoth', 'tkinter', 'openpyxl'):
    tmp = collect_all(module)
    datas += tmp[0]
    binaries += tmp[1]
    hiddenimports += tmp[2]

icon_path = __ROOT_PATH__ / 'dist' / 'DocConvert.ico'
icon_arg = str(icon_path) if icon_path.is_file() else None

a = Analysis(
    [str(__ROOT_PATH__ / 'main.py')],
    pathex=[str(__ROOT_PATH__)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='{target_name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_arg,
)
{collect_block}
"""


def _write_spec(onefile: bool) -> Path:
    SPEC_PATH.parent.mkdir(parents=True, exist_ok=True)
    SPEC_PATH.write_text(_render_spec(onefile=onefile), encoding="utf-8")
    return SPEC_PATH


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--onedir",
        action="store_true",
        help="Emit an onedir bundle instead of a single-file executable.",
    )
    parser.add_argument(
        "--clean",
        action="store_true",
        help="Remove the build/ and dist/ directories before building.",
    )
    args = parser.parse_args(argv)

    if args.clean:
        for sub in ("build", "dist"):
            target = ROOT / sub
            if target.exists():
                shutil.rmtree(target)

    spec_path = _write_spec(onefile=not args.onedir)

    pyinstaller = shutil.which("pyinstaller")
    if pyinstaller is None:
        print("ERROR: pyinstaller is not installed. Install with 'pip install .[build]'.", file=sys.stderr)
        return 1

    cmd = [pyinstaller, "--noconfirm", "--clean", str(spec_path)]
    print("+", " ".join(cmd))
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        return result.returncode

    base_name = DIST_NAME if not args.onedir else f"{DIST_NAME}-onedir"
    exe_candidate = ROOT / "dist" / f"{base_name}.exe"
    artefact_src = ROOT / "dist" / base_name
    if not artefact_src.exists() and not exe_candidate.exists():
        print(f"ERROR: expected artefact not found at {artefact_src}", file=sys.stderr)
        return 1
    artefact_src = artefact_src if artefact_src.exists() else exe_candidate

    final_dir = ROOT / "dist" / f"{DIST_NAME}-{_platform_tag()}"
    final_dir.mkdir(parents=True, exist_ok=True)
    if artefact_src.is_dir():
        if final_dir.exists():
            shutil.rmtree(final_dir)
        shutil.move(str(artefact_src), str(final_dir))
    else:
        shutil.copy2(artefact_src, final_dir / artefact_src.name)

    print(f"Built artefact staged at {final_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
